templates_path: templates
foldx_mutations_input_directory: "/data/raw_data/computational_data/mutatex_data/marinara/pold1/complexes/dna/6TNY_APT_pdbs/cryo-em/mutations/6TNYapt_78-1107_dna_model0_checked_Repair/"
mutation_list: "/data/raw_data/computational_data/mutatex_data/marinara/pold1/complexes/dna/6TNY_APT_pdbs/cryo-em/mutation_list.txt"
output:
   main_output_folder: "output"
   foldx_output_folder: "foldx_output"
   arpeggio_output_folder: "arpeggio_output"
scripts_parameters:
  ArpeggioInteractionPipeline:
    interface: False
    output_file: "arpeggio_output.csv"
    keep_proximal: False

